const { test, expect } = require('@playwright/test')

test('Verify keyboard action in Playwright', async ({ page }) => {
    await page.goto('https://gotranscript.com/text-compare')
    // await page.keyboard.down('PageDown')
    await page.locator('textarea[name="text1"]').fill('This is my first keyboard action method in playwright')
    await page.keyboard.press('Control+A')
    await page.keyboard.press('Control+C')
    // await page.locator('textarea[name="text2"]').click()
    // await page.keyboard.press('Control+V')
    await page.keyboard.down('Tab')
    await page.keyboard.press('Shift+Digit3')
    await page.keyboard.press('Shift+Digit5')
    // await page.locator('#recaptcha').click()
    // await expect(page.locator('.text-left')).toBeVisible()
    // await expect(page).toHaveURL('https://gotranscript.com/text-compare#diff')
    // await expect(page.locator('.alert-info')).toHaveText('This is my first keyboard action method in playwright')
    await page.waitForTimeout(4000) 
})